### ISSUE TITLE
请教：docker 镜像运行，初始化就提示错误。

### ISSUE THREAD

**Issue by sipgov** [trustyboy/xxqg-helper#38]
============================================================
内置驱动初始化失败
============================================================
Traceback (most recent call last):
  File "XueQG.py", line 40, in <module>
  File "func/Xuecore.py", line 87, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 76, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 157, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 252, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/lib/chromium/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

[7] Failed to execute script 'XueQG' due to unhandled exception!

**Comment by sipgov** [comment]
怎么回事？

**Comment by no1ajian** [comment]
一样的问题
