### ISSUE TITLE
Failed to execute script 'XueQG' due to unhandled exception!

### ISSUE THREAD

**Issue by yhyandye** [trustyboy/xxqg-helper#51]
Traceback (most recent call last):
  File "XueQG.py", line 47, in <module>
  File "func/score.py", line 55, in show_userScore
  File "func/score.py", line 17, in get_userScore
TypeError: 'NoneType' object is not subscriptable
[7] Failed to execute script 'XueQG' due to unhandled exception!
一运行就报错，查看日志显示如上，请问应该怎么解决啊？

**Comment by trustyboy** [comment]
#49
