### ISSUE TITLE
docker arm64 运行出错，麻烦大佬们看看啥原因

### ISSUE THREAD

**Issue by sipgov** [trustyboy/xxqg-helper#72]
下面是日志：

正在打开二维码登陆界面,请稍后...
Traceback (most recent call last):
  File "XueQG.py", line 41, in <module>
  File "func/Xuecore.py", line 131, in logging
  File "selenium/webdriver/remote/webdriver.py", line 333, in get
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 276.363
  (Session info: headless chrome=86.0.4240.111)

[7] Failed to execute script 'XueQG' due to unhandled exception!

**Comment by trustyboy** [comment]
超时了，多次几次看看。可能是设备性能不够

**Comment by Yy1614** [comment]
有没有教程啊，不会玩，源码已经下好了，但是不知道怎么运行。

**Comment by BoGe44** [comment]
那就好好学习，花时间学点东西就会玩了
